import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/modals/RegisterModal'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Nunito } from 'next/font/google'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className = {font.className}>
        {/* we use client only here to stop hydration errors (bug) */}
        <ClientOnly>
          <RegisterModal />
          <Navbar />
        </ClientOnly>
          {children}
      </body>
    </html>
  )
}
